{% set name = "fififly" %}
{% set version = "1.0.30" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_tag: main
  git_url: https://github.com/darioflute/fififly.git

build:
  
requirements:
  build:
    - setuptools
    - python

  run:
    - python
    - matplotlib >=3.0.2
    - numpy >=1.11
    - scipy
    - astropy >=3.0
    - pyqt
        
test:
  imports:
    - fififly
  commands:
    - scanmaker

about:
  home: https://github.com/darioflute/fififly
  license: GPL3
  license_file: LICENSE
  description: 'Library for reduction of non-standard FIFI-LS data.'
